version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:5000:5432"
    environment:
      POSTGRES_DB: gurkbot
      POSTGRES_USER: gurkbotdb
      POSTGRES_PASSWORD: gurkbotdb
    volumes:
      - ./bot/postgres/tables:/docker-entrypoint-initdb.d/

  gurkbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gurkbot
    init: true

    restart: on-failure
    env_file:
      - .env

    environment:
      - ENVIRONMENT=DOCKER-DEVELOPMENT
      - DATABASE_URL=postgres://gurkbotdb:gurkbotdb@postgres:5432/gurkbot

    volumes:
      - .:/bot

    depends_on:
      - postgres
